Repository MicrosoftDocs/partner-center-sdk, pull requests merged in 2020-12, with the labels that each got.

#118 Add throttling guidance when using SDK
  develop/api-throttling-guidance.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, partner-dashboard/svc, partnercenter-sdk/subsvc

#119 Update request-reseller-relationship.md
  develop/request-reseller-relationship.md
Labels: Change sent to author, partner-dashboard/svc, partnercenter-sdk/subsvc, ready-to-merge

#120 Update get-prices-for-microsoft-azure.md
  develop/get-prices-for-microsoft-azure.md
Labels: Change sent to author, do-not-merge, partner-dashboard/svc, partnercenter-sdk/subsvc
