Repository MicrosoftDocs/partner-center-sdk, pull requests merged in 2021-07, with the labels that each got.

#129 Missing variable assignment
  develop/enable-secure-app-model.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, partner-dashboard/svc, partnercenter-csp/subsvc

#131 Update get-invoice-unbilled-consumption-lineitems.md
  develop/get-invoice-unbilled-consumption-lineitems.md
Labels: Change sent to author, aq-pr-triaged, partner-dashboard/svc, partnercenter-sdk/subsvc, ready-to-merge

#132 Settings menu item name change
  develop/set-up-api-access-in-partner-center.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, partner-dashboard/svc, partnercenter-sdk/subsvc
